development:
  adapter: postgresql
  encoding: unicode
  database: homeyio_development
  pool: 5
  username: homeyio
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: homeyio_test
  pool: 5
  username: homeyio
  password:

